networks:
  gophkeepernet:
    name: gophkeepernet
    driver: bridge

volumes:
  gophkeeper_s3:

services:
  gophkeeper-db:
    image: gophkeeper_postgres:latest
    container_name: gophkeeper-db
    hostname: gophkeeper-db
    networks:
      - gophkeepernet
    ports:
      - "5542:5432" # Хост 5542 -> Контейнер 5432
    environment:
      - POSTGRES_USER=gophkeeper
      - POSTGRES_PASSWORD=gophkeeper_pswd
      - POSTGRES_DB=gophkeeper
  gophkeeper-s3:
    image: minio/minio:latest
    networks:
      - gophkeepernet
    container_name: gophkeeper-s3
    hostname: gophkeeper-s3
    ports:
      - "9000:9000" # Порт для API (куда будет ходить ваш Go-сервер)
      - "9001:9001" # Порт для Web-консоли (чтобы зайти глазами в браузере)
    environment:
      MINIO_ROOT_USER: gophkeeper          # Логин администратора S3
      MINIO_ROOT_PASSWORD: gophkeeper_pswd # Пароль администратора (минимум 8 символов)
    volumes:
      - gophkeeper_s3:/data                # Локальный Volume для сохранения файлов
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Автоматический инициализатор бакета
  gophkeeper-s3-init:
    image: minio/mc:latest
    networks:
      - gophkeepernet
    container_name: gophkeeper-s3-init
    hostname: gophkeeper-s3-init
    depends_on:
      - gophkeeper-s3 # Ждем, пока запустится основной контейнер S3
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      until /usr/bin/mc alias set local_s3 http://gophkeeper-s3:9000 gophkeeper gophkeeper_pswd; do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing local_s3/gophkeeper;
      echo 'Bucket gophkeeper-vault created successfully!';
      exit 0;
      "