networks:
  gophkeepernet:
    name: gophkeepernet
    driver: bridge

# pki:
#   server_ca_key_path: ".certs_private/server-ca.key"
#   device_ca_key_path: ".certs_private/device-ca.key"
#   device_ca_cert_path: "internal/shared/certs/assets/device-ca.crt"

services:
  gophkeeper-db:
    build:
      context: ../infra/database    # Контекстом сборки делаем саму папку с базой
      dockerfile: Dockerfile        # Dockerfile лежит прямо внутри этого контекста
    container_name: gophkeeper-db
    hostname: gophkeeper-db
    networks:
      - gophkeepernet
    ports:
      - "5542:5432" # Хост 5542 -> Контейнер 5432
    environment:
      - POSTGRES_USER=gophkeeper
      - POSTGRES_PASSWORD=gophkeeper_pswd
      - POSTGRES_DB=gophkeeper

  gophkeeper-server:
    build:
      context: ../                  # Корень проекта, чтобы COPY видела cmd/
      dockerfile: infra/gophkeeper-server/Dockerfile
    container_name: gophkeeper-server
    hostname: gophkeeper-server
    networks:
      - gophkeepernet
    ports:
      - "443:443"   # Защищенный gRPC-порт для mTLS клиентов

    volumes:
      - ../.certs_private:/app/.certs_private:ro
      - ../internal/shared/certs/assets:/app/certs_public:ro

    environment:
      - GOPHKEEPER_SERVER_SERVER_BIND_GRPC=:443
      - GOPHKEEPER_SERVER_STORAGE_POSTGRES_DSN=postgres://gophkeeper:gophkeeper_pswd@gophkeeper-db:5432/gophkeeper?sslmode=disable
      - GOPHKEEPER_SERVER_PKI_SERVER_CA_KEY_PATH=.certs_private/server-ca.key
      - GOPHKEEPER_SERVER_PKI_DEVICE_CA_KEY_PATH=.certs_private/device-ca.key


    depends_on:
      gophkeeper-db:
        condition: service_healthy
    restart: unless-stopped